import { tmpdir } from "node:os";
import { join } from "node:path";
import { writeFile, mkdir } from "node:fs/promises";
import { PNG } from "pngjs";

const ROOT = new URL("../", import.meta.url);
// The DOM header uses the exact production wordmark PNG (gitignored local
// asset), so only the 3D scene mark still needs an occupancy trace.
const ASSETS = [
  {
    name: "logo",
    url: "https://pumpgame.ir/images/landing/pump-logo.png",
    // ~1.9:1 source aspect; dense enough that the stepped silhouette survives
    // quantization instead of reading as a blob.
    width: 40,
    height: 21,
  },
];

function sample(png, targetWidth, targetHeight) {
  const rows = [];
  const tints = {};

  for (let gy = 0; gy < targetHeight; gy++) {
    let row = "";
    for (let gx = 0; gx < targetWidth; gx++) {
      const x0 = Math.floor((gx * png.width) / targetWidth);
      const x1 = Math.max(x0 + 1, Math.floor(((gx + 1) * png.width) / targetWidth));
      const y0 = Math.floor((gy * png.height) / targetHeight);
      const y1 = Math.max(y0 + 1, Math.floor(((gy + 1) * png.height) / targetHeight));
      let alpha = 0;
      let red = 0;
      let green = 0;
      let blue = 0;
      let samples = 0;

      for (let y = y0; y < y1; y++) {
        for (let x = x0; x < x1; x++) {
          const i = (y * png.width + x) * 4;
          const a = png.data[i + 3] / 255;
          alpha += a;
          red += png.data[i] * a;
          green += png.data[i + 1] * a;
          blue += png.data[i + 2] * a;
          samples += a;
        }
      }

      const occupied = alpha / ((x1 - x0) * (y1 - y0)) >= 0.22;
      row += occupied ? "1" : "0";
      if (occupied && samples > 0) {
        const rgb = [red, green, blue].map((value) => Math.round(value / samples));
        const hex = `#${rgb.map((value) => value.toString(16).padStart(2, "0")).join("")}`;
        if (hex.toLowerCase() !== "#f42a8f") tints[`${gx},${gy}`] = hex;
      }
    }
    rows.push(row);
  }

  return { rows, tints };
}

for (const asset of ASSETS) {
  const response = await fetch(asset.url);
  if (!response.ok) throw new Error(`Failed to fetch ${asset.url}: ${response.status}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  const tempPath = join(tmpdir(), `pump-${asset.name}.png`);
  await writeFile(tempPath, bytes);

  const png = PNG.sync.read(bytes);
  const { rows, tints } = sample(png, asset.width, asset.height);
  const outDir = new URL("lib/brand/", ROOT);
  await mkdir(outDir, { recursive: true });
  const source = `// Generated by scripts/trace-brand.mjs from a temporary reference image.\nexport const MAP = ${JSON.stringify(rows, null, 2)} as const;\n\nexport const TINTS: Readonly<Record<string, string>> = ${JSON.stringify(tints, null, 2)};\n`;
  await writeFile(new URL(`${asset.name}-map.ts`, outDir), source);
  console.log(`Traced ${asset.name} (${png.width}x${png.height}) via ${tempPath}`);
}
